### ISSUE TITLE
How to obtain the tag image?

### ISSUE THREAD

**Issue by adriendomoison** [whitelok/ldbm-image-background-remover#1]

**Comment by whitelok** [comment]
You have draw the tag image with Image software by your self. Or I can help
you to tag one.

Adrien <notifications@github.com> 于2018年10月12日周五 下午3:28写道：

**Comment by adriendomoison** [comment]
Thank you @whitelok, so no way to do that automatically? I am looking for a way to remove the background of a lot of images automatically. Any suggestion?

**Comment by whitelok** [comment]
Seems there are some DL model for marking the front and background called target segmentation. But it is not the content of this repository.

**Comment by adriendomoison** [comment]
Yes, of course, I understand that. Thank you so much for the tip, highly appreciated!

**Comment by whitelok** [comment]
Thanks and close this issue according to https://github.com/whitelok/ldbm-image-background-remover/issues/1#issuecomment-429597884
